# Generated by Django 2.2.12 on 2020-06-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='log_modf_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_log', models.CharField(max_length=100)),
                ('row_parent', models.CharField(max_length=100)),
                ('id_parent', models.BooleanField(default=False)),
                ('date_modf', models.DateField(auto_now=True)),
                ('id_end', models.BooleanField(default=False)),
                ('inf_modf', models.CharField(max_length=150)),
                ('arg_modf', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spr_fields_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_field', models.CharField(max_length=50, unique=True)),
                ('js_data', models.CharField(max_length=500)),
                ('id_key', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='spr_param_proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_param', models.CharField(max_length=150)),
                ('str_param', models.CharField(max_length=150)),
                ('key_param', models.CharField(max_length=50, null=True, unique=True)),
                ('path_proj', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spr_pswcl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pswcl', models.CharField(max_length=10, unique=True, verbose_name='Логин гостВхода')),
                ('date_add', models.DateField(auto_now=True, verbose_name='Дата создЗаписи')),
                ('meaning', models.CharField(blank=True, max_length=50, null=True, verbose_name='Смысл/значение pswcl')),
                ('for_use', models.CharField(default='empty', max_length=20, verbose_name='Владелец записи')),
            ],
        ),
        migrations.CreateModel(
            name='spr_usedIdent',
            fields=[
                ('usedId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('s_info', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='templ_buf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(blank=True, max_length=150, null=True)),
                ('val_buf', models.CharField(blank=True, max_length=250, null=True)),
                ('val_any', models.CharField(blank=True, max_length=250, null=True)),
                ('id_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='templ_buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('id_parent', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50)),
                ('date_modf', models.DateField(auto_now=True)),
                ('s_info', models.CharField(max_length=150)),
                ('val_copy', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='spr_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_param', models.CharField(max_length=2000, verbose_name='dict параметры')),
                ('id_used', models.BooleanField(verbose_name='Актуальность настройки')),
                ('usedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spr_usedIdent', verbose_name='СтрИдентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='log_acivity_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rec', models.DateField(auto_now_add=True, verbose_name='НачДатаЛогина')),
                ('date_last', models.DateField(auto_now=True, verbose_name='ПослДатаПосещ')),
                ('mm', models.SmallIntegerField(verbose_name='месяц')),
                ('yy', models.SmallIntegerField(verbose_name='Год')),
                ('id_record', models.SmallIntegerField(default=1, verbose_name='Индикатор')),
                ('counter_login', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Журнал активности',
            },
        ),
    ]
