# Generated by Django 2.2.12 on 2020-06-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spr_fields_models',
            name='id_key',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
    ]
