# Generated by Django 2.2.12 on 2020-07-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templ_buf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentuser', models.IntegerField()),
                ('advData', models.TextField(max_length=500)),
                ('js_struct', models.CharField(default='{}', max_length=300)),
            ],
        ),
    ]
