# Generated by Django 2.2.12 on 2020-07-18 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advuser', '0002_templ_buf'),
    ]

    operations = [
        migrations.AddField(
            model_name='templ_buf',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templ_buf',
            name='parentuser',
            field=models.CharField(max_length=150),
        ),
    ]
